version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: docker build -t ziadhaytham88/myimage:${CIRCLE_SHA1} .
      - run: echo "$Zozaa882001" | docker login -u "$ziadhaytham8" --password-stdin
      - run: docker push ziadhaytham8/myimage:${CIRCLE_SHA1}
