version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t udagram-reveseproxy ./udagram-reveseproxy
            docker tag udagram-api-feed ziadhaytham88/udagram-api-feed:v1
            docker tag udagram-api-user ziadhaytham88/udagram-api-user:v1
            docker tag udagram-frontend ziadhaytham88/udagram-frontend:v1
            docker tag udagram-reveseproxy ziadhaytham88/udagram-reverseproxy:v1
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ziadhaytham88/udagram-api-feed:v1
            docker push ziadhaytham88/ziadhaytham88/udagram-api-user:v1
            docker push ziadhaytham88/udagram-frontend:v1
            docker push ziadhaytham88/udagram-reverseproxy:v1
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: my-docker-context